namespace AgyLogger.Cli.Models.Proxy;

/// <summary>
/// Strongly-typed representation of an LLM response reconstructed from raw text or streaming SSE chunks.
/// </summary>
public sealed record class ParsedResponse
{
    /// <summary>
    /// Finish reason emitted by the provider (e.g. "STOP", "MAX_TOKENS", "end_turn").
    /// </summary>
    public string? FinishReason { get; init; }

    /// <summary>
    /// Compact JSON representation of token usage metadata.
    /// </summary>
    public string? UsageJson { get; init; }

    /// <summary>
    /// Reconstructed thinking / reasoning text.
    /// </summary>
    public string? Thinking { get; init; }

    /// <summary>
    /// Reconstructed assistant message text.
    /// </summary>
    public string? AssistantText { get; init; }

    /// <summary>
    /// Invocations of external tools generated by the model.
    /// </summary>
    public IReadOnlyList<ParsedToolCall> ToolCalls { get; init; } = [];

    /// <summary>
    /// Indicates whether any content was decoded. If false, renderer emits "_(no content decoded)_".
    /// </summary>
    public bool HasContent => !string.IsNullOrEmpty(Thinking) ||
                              !string.IsNullOrEmpty(AssistantText) ||
                              ToolCalls.Count > 0 ||
                              !string.IsNullOrEmpty(FinishReason) ||
                              !string.IsNullOrEmpty(UsageJson);

    /// <summary>
    /// Raw unparsed response text if non-streaming or fallback.
    /// </summary>
    public string? RawFallback { get; init; }
}