namespace AgyLogger.Cli.Models.Proxy;

/// <summary>
/// Strongly-typed representation of an LLM request extracted by a wire format parser.
/// Decouples JSON parsing from Markdown document rendering.
/// </summary>
public sealed record class ParsedRequest
{
    /// <summary>
    /// Extracted model identifier (e.g. "gemini-2.5-pro", "claude-3-7-sonnet-20250219").
    /// </summary>
    public string? Model { get; init; }

    /// <summary>
    /// System instruction text or prompt.
    /// </summary>
    public string? SystemPrompt { get; init; }

    /// <summary>
    /// Sampling and execution parameters (temperature, topP, maxOutputTokens, thinkingConfig, etc.).
    /// </summary>
    public IReadOnlyList<KeyValuePair<string, string>> Parameters { get; init; } = [];

    /// <summary>
    /// Tool and function declarations exposed to the model.
    /// </summary>
    public IReadOnlyList<ParsedToolDeclaration> Tools { get; init; } = [];

    /// <summary>
    /// Turn-by-turn conversation messages.
    /// </summary>
    public IReadOnlyList<ParsedMessage> Messages { get; init; } = [];

    /// <summary>
    /// Formatted raw text or JSON if parser fell back to raw representation.
    /// </summary>
    public string? RawFallback { get; init; }

    /// <summary>
    /// Optional warning banner if parsing encountered non-fatal errors.
    /// </summary>
    public string? ParseErrorWarning { get; init; }
}

/// <summary>
/// Tool and function declaration exposed to the model.
/// </summary>
public sealed record class ParsedToolDeclaration
{
    public required string Name { get; init; }
    public string? Description { get; init; }
    public string? ParameterSchemaJson { get; init; }
}

/// <summary>
/// Turn-by-turn conversation message.
/// </summary>
public sealed record class ParsedMessage
{
    public int Index { get; init; }
    public required string Role { get; init; } // "user" or "model" (Gemini) / "assistant"
    public IReadOnlyList<ParsedContentPart> Parts { get; init; } = [];
}

/// <summary>
/// Content part within a conversation message.
/// </summary>
public sealed record class ParsedContentPart
{
    public string? Text { get; init; }
    public bool IsThinking { get; init; }
    public ParsedToolCall? ToolCall { get; init; }
    public ParsedToolResult? ToolResult { get; init; }
    public string? InlineDataPlaceholder { get; init; }
    public string? RawJson { get; init; }
}

/// <summary>
/// Tool or function invocation generated by the model.
/// </summary>
public sealed record class ParsedToolCall
{
    public required string Name { get; init; }
    public string Id { get; init; } = string.Empty;
    public required string ArgumentsJson { get; init; }
}

/// <summary>
/// Tool execution output returned to the model.
/// </summary>
public sealed record class ParsedToolResult
{
    public required string Name { get; init; }
    public string Id { get; init; } = string.Empty;
    public required string Content { get; init; }
    public bool IsError { get; init; }
}